### ISSUE TITLE
Wrong access specifiers or package division

### ISSUE THREAD

**Issue by orat** [MobMonRob/JRTDE#9]
Mit swig generierter Code wurde in zwei sub packagages aufgeteilt:
1. std
2. urtde
Einige Konstruktoren und Methoden der Klassen in std sind allerdings "protected". So klappt der Zugriff von den generierten Klassen in urtde nicht mehr.

**Comment by mosabkassar** [comment]
Hallo Oli,

Ich habe das vermutet, da im Swig ein spiezielle Interface für Std gibt und mit dem sollten wir arbeiten.

Z.B.
%{
#include "functions.h"
%}
**%include "std_vector.i"**
namespace std {
  %template(VecDouble) vector<double>;
  %template(VecVecdouble) vector< vector<double> >;
}

%include "functions.h"

////////////////////////
https://stackoverflow.com/questions/5262479/vector-vector-double-argument-with-swig-and-python
////////////////////////////////////

Aber es funktoiniert bei mir leider nicht.

**Comment by orat** [comment]
Ein spezielles bereits vorhandenes Interface zum Wrappen von std Klassen zu verwenden klingt vernünftig. Im Prinzip scheint das doch auch zu funktionieren. Nur eben die access modifier sind falsch. Testweise könntest Du die ja auch mal im generierten Code ersetzen und testen ob das dann funktioniert.

**Comment by orat** [comment]
Das Problem scheint ja nun gelöst zu sein. Vorsichtshalber bitte noch mal testen.

**Comment by orat** [comment]
fixed
